import React from 'react';

export default function CoverPage({ result }) {
  const reco = result.planner_summary?.recommendation?.replace(/_/g, ' ').toUpperCase() || 'PROCEED WITH CONDITIONS';
  
  return (
    <div className="report-page cover-page flex flex-col justify-between" style={{ height: '100%', minHeight: '297mm' }}>
      <div>
        <div className="flex items-center gap-3 mb-16">
          <div className="w-10 h-10 bg-black flex items-center justify-center rounded-lg">
            <div className="w-3 h-3 bg-white rounded-full"></div>
          </div>
          <div>
            <h1 className="font-bold text-xl tracking-tight text-black m-0 leading-none">Urban Intelligence OS</h1>
            <p className="text-xs text-gray-500 uppercase tracking-widest mt-1">Official OS Intelligence Briefing</p>
          </div>
        </div>

        <div className="mt-32">
          <p className="text-sm font-bold uppercase tracking-widest text-emerald-600 mb-4">Infrastructure Policy Assessment</p>
          <h1 className="text-5xl font-bold text-gray-900 leading-tight mb-6">
            {result.location}
          </h1>
          <h2 className="text-3xl text-gray-400 font-medium mb-12">
            Intervention: {result.policy_type?.replace(/_/g, ' ').toUpperCase()}
          </h2>

          <div className="inline-block px-6 py-3 bg-gray-100 border border-gray-200 rounded-lg mb-16">
            <p className="text-xs text-gray-500 uppercase tracking-widest mb-1">Final Recommendation</p>
            <p className="text-xl font-bold text-gray-900">{reco}</p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-8 border-t border-gray-200 pt-8 pb-12">
        <div>
          <p className="text-xs text-gray-500 uppercase tracking-widest mb-2">Simulated ROI</p>
          <p className="text-3xl font-bold text-gray-900">{result.roi_score?.toFixed(2)}</p>
        </div>
        <div>
          <p className="text-xs text-gray-500 uppercase tracking-widest mb-2">Timeline</p>
          <p className="text-3xl font-bold text-gray-900">{result.timeline_months} mo</p>
        </div>
        <div>
          <p className="text-xs text-gray-500 uppercase tracking-widest mb-2">Sustainability</p>
          <p className="text-3xl font-bold text-gray-900">{result.impact?.sustainability_score?.toFixed(0)}<span className="text-lg text-gray-400">/100</span></p>
        </div>
        <div>
          <p className="text-xs text-gray-500 uppercase tracking-widest mb-2">Community</p>
          <p className="text-3xl font-bold text-gray-900">{result.socio_economic?.community_impact_score}<span className="text-lg text-gray-400">/100</span></p>
        </div>
      </div>
      
      <div className="text-xs text-gray-400 pt-4 border-t border-gray-100">
        Generated by AI Planning Engine on {new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })} at {new Date().toLocaleTimeString('en-IN')}
      </div>
    </div>
  );
}
