import React from 'react';
import './report.css';

import CoverPage from './CoverPage';
import ExecutiveSummary from './ExecutiveSummary';
import TrafficReport from './TrafficReport';
import EnvironmentalReport from './EnvironmentalReport';
import CommunityImpactReport from './CommunityImpactReport';

// The PrintableReport component wraps all report pages.
export default function PrintableReport({ result }) {
  if (!result) return null;

  return (
    <div className="printable-report-container">
      <CoverPage result={result} />
      <ExecutiveSummary result={result} />
      <TrafficReport result={result} />
      <EnvironmentalReport result={result} />
      <CommunityImpactReport result={result} />
      
      {/* Page 7 - Final Planner Recommendation is basically the cover page / executive summary 
          combined, but we can add a specific sign-off page if requested.
          The Executive Summary handles most of the PlannerRecommendation content. 
      */}
      <div className="report-page" style={{ minHeight: 'auto', pageBreakAfter: 'avoid' }}>
        <div className="report-header mt-10">
          <h2>6.0 Final Endorsement</h2>
          <div className="report-line"></div>
        </div>
        <div className="border border-gray-300 p-8 rounded-lg bg-gray-50">
          <p className="text-sm text-gray-700 uppercase tracking-widest mb-2 font-bold">System Verdict</p>
          <p className="text-2xl font-bold text-gray-900 mb-6">{result.planner_summary?.recommendation?.replace(/_/g, ' ').toUpperCase()}</p>
          <p className="text-sm text-gray-800 leading-relaxed">
            Based on the multi-domain simulation combining traffic (XGBoost), environmental (CPCB models), and socio-economic heuristics, 
            this project presents an ROI of {result.roi_score?.toFixed(2)} over {result.timeline_months} months.
          </p>
          <div className="mt-12 flex justify-between items-end border-t border-gray-300 pt-6">
            <div>
              <p className="text-xs text-gray-500 uppercase tracking-widest">Generated By</p>
              <p className="text-sm font-bold text-gray-900 mt-1">Urban Intelligence OS AI Engine</p>
            </div>
            <div>
              <p className="text-xs text-gray-500 uppercase tracking-widest text-right">Date of Assessment</p>
              <p className="text-sm font-bold text-gray-900 mt-1 text-right">{new Date().toLocaleDateString('en-IN')}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
